port: 443

#Log level 2 to see whats going on
log_level: 2

#This is your Database config:
db_host: 'localhost'
db_user: 'root'
db_pass: 'pass'
db_database: 'siri'

#For Generating Certs for iPhones. Has 2 hosts, so that you can use guzzoni on a 4S, 
#and your server also using the same instance.
ca_name: 'SiriProxyCA'
server1: 'guzzoni.apple.com'
server2: 'your.siri.proxy.server.com'

#For your email configuration. Edit to your email address and set send_email to 'ON'. 
#Also plase notice that you have to configure sendmail for you pc if its required
#It is possible that this email will be delivered to your spam/junk folder.
#html formated message is default
send_email: 'OFF' 
email_from: 'The Three Little Pigs'
email_to: 'youremail'
email_subject: 'A 4S Key Expired' 
email_message: '<p>Hello, </br> this is an automated message from The Three Little Pigs SiriProxy.
</br> A 4S key on the database has expired!</p><p>Please do not reply to this message</p>'

plugins:
    # NOTE: run bundle after changing plugin configurations to update required gems

    - name: 'Example'
      path: './plugins/siriproxy-example'

    # - name: 'Thermostat'
    #   git: 'git://github.com/plamoni/SiriProxy-Thermostat.git'
    #   host: '192.168.2.71' 

    # - name: 'Twitter'
    #   path: './plugins/siriproxy-twitter' # path works just like specifing in gemfile 
    #   consumer_key: "YOUR_KEY" 
    #   consumer_secret: "YOUR_SECRET"
    #   oauth_token: "YOUR_TOKEN" 
    #   oauth_token_secret: "YOUR_TOKEN_SECRET"

    # Note: Eliza should not be run with other plugins
    # - name: 'Eliza'
    #   path: './plugins/siriproxy-eliza' # path works just like specifing in gemfile 

    # Below are not actual plugins, just further example of config options

    # - SimplePlugin # simple syntax for plugins that are in rubygems and have no config 

    # - name: 'AnotherPlugin'
    #   git: 'git://github.com/netpro2k/SiriProxy-AnotherPlugin.git' # git works just like specifying in Gemfile
